const loginForm = {
    username: () => cy.get('input[autocomplete="username"]'),
    password: () => cy.get('input[autocomplete="current-password"]'),
    submit: () => cy.get('#app > div.page > div > section > form > div.form__buttons > div:nth-child(3) > button').click()
}

const goToNeeds = ({ url, routes, employer }) => {
    cy.log('Переход на страницу авторизации')
    cy.visit(url + routes.login, { timeout: 10000 })

    cy.log('Ввод email')
    loginForm.username()
        .should('be.visible')
        .type(employer.login)

    cy.log('Ввод пароля')
    loginForm.password()
        .should('be.visible')
        .type(employer.password)

    cy.log('Нажатие на кнопку войти')
    loginForm.submit()
        .should('be.visible')

    cy.log('Проверка успешного входа')
    cy.url().should('include', 'https://dev.profteam.su/account/main')
}

describe ('создание новой вакансии работодателем на пк', () => {
    beforeEach(function () {
        cy.viewport(1920, 1080);
        cy.fixture('config').then(goToNeeds)
    })

    it("Создание потребности на пк 1", ()=>{
        cy.log('Нажать кнопку на переход на страницу с потребностями')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav > div:nth-child(6)")
            .click({timeout: 1000})
        cy.log('Нажать кнопку для создание потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.needs-block__filters-wrapper > button")
            .click({timeout: 1000})
        cy.log('Ввод потребности')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(1) > div > input")
            .click({timeout:1000}).type("Сварщик")
        cy.log('Нажать кнопку для выбора оплаты')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(2) > div > div.salary-field__wrapper.salary-field__wrapper--bottom > div > label:nth-child(1)")
            .click({timeout:1000})
        cy.log('Ввод минимальной зарплаты')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(2) > div > div:nth-child(3) > div:nth-child(1) > div > input")
            .click({timeout:1000}).type("1000")
        cy.log('Ввод максимальной зарплаты')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(2) > div > div:nth-child(3) > div:nth-child(2) > div > input")
            .click({timeout:1000}).type("2500")
        cy.log('Ввод обязанностей')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(3) > div > textarea")
            .click({timeout:1000}).type("Варить металл")
        cy.log('Ввод требований')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(4) > div > textarea")
            .click({timeout:1000}).type("150 лет опыта работа")
        cy.log('Нажать кнопку создать потребность')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div.form__buttons > button")
            .click({timeout:1000})
        cy.log('Публикация потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.infinite-loader.need-list > div:nth-child(1) > div > div.need-item__footer-wrapper > div > div.need-footer__button-wrapper > button.button.button__background-color-green.button__size-small.button__color-white")
            .click({timeout:1000})
    })
    it("Создание потребности на пк 2", ()=>{
        cy.log('Нажать кнопку на переход на страницу с потребностями')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav > div:nth-child(6)")
            .click({timeout: 1000})
        cy.log('Нажать кнопку для создание потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.needs-block__filters-wrapper > button")
            .click({timeout: 1000})
        cy.log('Ввод потребности')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(1) > div > input")
            .click({timeout:1000}).type("Сварщик")
        cy.log('Нажать кнопку для выбора оплаты')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(2) > div > div.salary-field__wrapper.salary-field__wrapper--bottom > div > label:nth-child(1)")
            .click({timeout:1000})
        cy.log('Ввод минимальной зарплаты')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(2) > div > div:nth-child(3) > div:nth-child(1) > div > input")
            .click({timeout:1000}).type("1000")
        cy.log('Ввод максимальной зарплаты')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(2) > div > div:nth-child(3) > div:nth-child(2) > div > input")
            .click({timeout:1000}).type("2500")
        cy.log('Ввод обязанностей')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(3) > div > textarea")
            .click({timeout:1000}).type("Варить металл")
        cy.log('Ввод требований')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(4) > div > textarea")
            .click({timeout:1000}).type("150 лет опыта работа")
        cy.log('Нажать на выпадающий список')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(5) > div > div > div")
            .click({timeout:1000})
        cy.log('Выбор пункта дистант')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(5) > div > div > div.form-select__items > div:nth-child(2)")
            .click({timeout:1000})
        cy.log('Нажать кнопку создать потребность')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div.form__buttons > button")
            .click({timeout:1000})
        cy.log('Публикация потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.infinite-loader.need-list > div:nth-child(1) > div > div.need-item__footer-wrapper > div > div.need-footer__button-wrapper > button.button.button__background-color-green.button__size-small.button__color-white")
            .click({timeout:1000})
    })
    it("Создание потребности на пк 3", ()=>{
        cy.log('Нажать кнопку на переход на страницу с потребностями')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav > div:nth-child(6)")
            .click({timeout: 1000})
        cy.log('Нажать кнопку для создание потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.needs-block__filters-wrapper > button")
            .click({timeout: 1000})
        cy.log('Ввод потребности')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(1) > div > input")
            .click({timeout:1000}).type("Сварщик")
        cy.log('Нажать кнопку для выбора оплаты')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(2) > div > div.salary-field__wrapper.salary-field__wrapper--bottom > div > label:nth-child(1)")
            .click({timeout:1000})
        cy.log('Ввод минимальной зарплаты')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(2) > div > div:nth-child(3) > div:nth-child(1) > div > input")
            .click({timeout:1000}).type("1000")
        cy.log('Ввод максимальной зарплаты')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(2) > div > div:nth-child(3) > div:nth-child(2) > div > input")
            .click({timeout:1000}).type("2500")
        cy.log('Ввод обязанностей')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(3) > div > textarea")
            .click({timeout:1000}).type("Варить металл")
        cy.log('Ввод требований')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(4) > div > textarea")
            .click({timeout:1000}).type("150 лет опыта работа")
        cy.log('Нажать на выпадающий список')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(5) > div > div > div")
            .click({timeout:1000})
        cy.log('Выбор пункта совмещенный')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(5) > div > div > div.form-select__items > div:nth-child(3)")
            .click({timeout:1000})
        cy.log('Нажать кнопку создать потребность')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div.form__buttons > button")
            .click({timeout:1000})
        cy.log('Публикация потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.infinite-loader.need-list > div:nth-child(1) > div > div.need-item__footer-wrapper > div > div.need-footer__button-wrapper > button.button.button__background-color-green.button__size-small.button__color-white")
            .click({timeout:1000})
    })
    it("Создание потребности на пк 4", ()=>{
        cy.log('Нажать кнопку на переход на страницу с потребностями')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav > div:nth-child(6)")
            .click({timeout: 1000})
        cy.log('Нажать кнопку для создание потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.needs-block__filters-wrapper > button")
            .click({timeout: 1000})
        cy.log('Ввод потребности')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(1) > div > input")
            .click({timeout:1000}).type("Сварщик")
        cy.log('Ввод обязанностей')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(3) > div > textarea")
            .click({timeout:1000}).type("Варить металл")
        cy.log('Ввод требований')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(4) > div > textarea")
            .click({timeout:1000}).type("150 лет опыта работа")
        cy.log('Нажать кнопку создать потребность')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div.form__buttons > button")
            .click({timeout:1000})
        cy.log('Публикация потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.infinite-loader.need-list > div:nth-child(1) > div > div.need-item__footer-wrapper > div > div.need-footer__button-wrapper > button.button.button__background-color-green.button__size-small.button__color-white")
            .click({timeout:1000})
    })
    it("Создание потребности на пк 5", ()=>{
        cy.log('Нажать кнопку на переход на страницу с потребностями')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav > div:nth-child(6)")
            .click({timeout: 1000})
        cy.log('Нажать кнопку для создание потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.needs-block__filters-wrapper > button")
            .click({timeout: 1000})
        cy.log('Ввод потребности')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(1) > div > input")
            .click({timeout:1000}).type("Сварщик")
        cy.log('Ввод обязанностей')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(3) > div > textarea")
            .click({timeout:1000}).type("Варить металл")
        cy.log('Ввод требований')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(4) > div > textarea")
            .click({timeout:1000}).type("150 лет опыта работа")
        cy.log('Нажать на выпадающий список')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(5) > div > div > div")
            .click({timeout:1000})
        cy.log('Выбор пункта дистант')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(5) > div > div > div.form-select__items > div:nth-child(2)")
            .click({timeout:1000})
        cy.log('Нажать кнопку создать потребность')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div.form__buttons > button")
            .click({timeout:1000})
        cy.log('Публикация потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.infinite-loader.need-list > div:nth-child(1) > div > div.need-item__footer-wrapper > div > div.need-footer__button-wrapper > button.button.button__background-color-green.button__size-small.button__color-white")
            .click({timeout:1000})
    })
    it("Создание потребности на пк 6", ()=>{
        cy.log('Нажать кнопку на переход на страницу с потребностями')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav > div:nth-child(6)")
            .click({timeout: 1000})
        cy.log('Нажать кнопку для создание потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.needs-block__filters-wrapper > button")
            .click({timeout: 1000})
        cy.log('Ввод потребности')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(1) > div > input")
            .click({timeout:1000}).type("Сварщик")
        cy.log('Ввод обязанностей')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(3) > div > textarea")
            .click({timeout:1000}).type("Варить металл")
        cy.log('Ввод требований')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(4) > div > textarea")
            .click({timeout:1000}).type("150 лет опыта работа")
        cy.log('Нажать на выпадающий список')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(5) > div > div > div")
            .click({timeout:1000})
        cy.log('Выбор пункта совмещенный')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(5) > div > div > div.form-select__items > div:nth-child(3)")
            .click({timeout:1000})
        cy.log('Нажать кнопку создать потребность')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div.form__buttons > button")
            .click({timeout:1000})
        cy.log('Публикация потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.infinite-loader.need-list > div:nth-child(1) > div > div.need-item__footer-wrapper > div > div.need-footer__button-wrapper > button.button.button__background-color-green.button__size-small.button__color-white")
            .click({timeout:1000})
    })
    it("Создание потребности на пк 7", ()=>{
        cy.log('Нажать кнопку на переход на страницу с потребностями')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav > div:nth-child(6)")
            .click({timeout: 1000})
        cy.log('Нажать кнопку для создание потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.needs-block__filters-wrapper > button")
            .click({timeout: 1000})
        cy.log('Ввод потребности')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(1) > div > input")
            .click({timeout:1000}).type("Сварщик")
        cy.log('Нажать кнопку для выбора оплаты')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(2) > div > div.salary-field__wrapper.salary-field__wrapper--bottom > div > label:nth-child(3)")
            .click({timeout:1000})
        cy.log('Ввод зарплаты')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(2) > div > div:nth-child(3) > div > div > input")
            .click({timeout:1000}).type("1000")
        cy.log('Ввод обязанностей')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(3) > div > textarea")
            .click({timeout:1000}).type("Варить металл")
        cy.log('Ввод требований')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(4) > div > textarea")
            .click({timeout:1000}).type("150 лет опыта работа")
        cy.log('Нажать кнопку создать потребность')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div.form__buttons > button")
            .click({timeout:1000})
        cy.log('Публикация потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.infinite-loader.need-list > div:nth-child(1) > div > div.need-item__footer-wrapper > div > div.need-footer__button-wrapper > button.button.button__background-color-green.button__size-small.button__color-white")
            .click({timeout:1000})
    })
    it("Создание потребности на пк 8", ()=>{
        cy.log('Нажать кнопку на переход на страницу с потребностями')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav > div:nth-child(6)")
            .click({timeout: 1000})
        cy.log('Нажать кнопку для создание потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.needs-block__filters-wrapper > button")
            .click({timeout: 1000})
        cy.log('Ввод потребности')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(1) > div > input")
            .click({timeout:1000}).type("Сварщик")
        cy.log('Нажать кнопку для выбора оплаты')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(2) > div > div.salary-field__wrapper.salary-field__wrapper--bottom > div > label:nth-child(3)")
            .click({timeout:1000})
        cy.log('Ввод зарплаты')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(2) > div > div:nth-child(3) > div > div > input")
            .click({timeout:1000}).type("1000")
        cy.log('Ввод обязанностей')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(3) > div > textarea")
            .click({timeout:1000}).type("Варить металл")
        cy.log('Ввод требований')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(4) > div > textarea")
            .click({timeout:1000}).type("150 лет опыта работа")
        cy.log('Нажать на выпадающий список')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(5) > div > div > div")
            .click({timeout:1000})
        cy.log('Выбор пункта дистант')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(5) > div > div > div.form-select__items > div:nth-child(2)")
            .click({timeout:1000})
        cy.log('Нажать кнопку создать потребность')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div.form__buttons > button")
            .click({timeout:1000})
        cy.log('Публикация потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.infinite-loader.need-list > div:nth-child(1) > div > div.need-item__footer-wrapper > div > div.need-footer__button-wrapper > button.button.button__background-color-green.button__size-small.button__color-white")
            .click({timeout:1000})
    })
    it("Создание потребности на пк 9", ()=>{
        cy.log('Нажать кнопку на переход на страницу с потребностями')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav > div:nth-child(6)")
            .click({timeout: 1000})
        cy.log('Нажать кнопку для создание потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.needs-block__filters-wrapper > button")
            .click({timeout: 1000})
        cy.log('Ввод потребности')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(1) > div > input")
            .click({timeout:1000}).type("Сварщик")
        cy.log('Нажать кнопку для выбора оплаты')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(2) > div > div.salary-field__wrapper.salary-field__wrapper--bottom > div > label:nth-child(3)")
            .click({timeout:1000})
        cy.log('Ввод зарплаты')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(2) > div > div:nth-child(3) > div > div > input")
            .click({timeout:1000}).type("1000")
        cy.log('Ввод обязанностей')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(3) > div > textarea")
            .click({timeout:1000}).type("Варить металл")
        cy.log('Ввод требований')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(4) > div > textarea")
            .click({timeout:1000}).type("150 лет опыта работа")
        cy.log('Нажать на выпадающий список')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(5) > div > div > div")
            .click({timeout:1000})
        cy.log('Выбор пункта совмещенный')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div:nth-child(1) > div.form__labels > div > div:nth-child(5) > div > div > div.form-select__items > div:nth-child(3)")
            .click({timeout:1000})
        cy.log('Нажать кнопку создать потребность')
        cy.get("body > div:nth-child(15) > div.desktop-modal > div > div.vacancy-need-wrapper > form > div.form__buttons > button")
            .click({timeout:1000})
        cy.log('Публикация потребности')
        cy.get("#app > div.page > div > div.page-navigation > div.page-nav__mobile > div:nth-child(7) > section > div > div.infinite-loader.need-list > div:nth-child(1) > div > div.need-item__footer-wrapper > div > div.need-footer__button-wrapper > button.button.button__background-color-green.button__size-small.button__color-white")
            .click({timeout:1000})
    })
})